nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            max_age: 3600
        '^/api/small-export/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS']
            expose_headers: ['Content-Disposition', 'Content-Type']
            max_age: 3600
        '^/api/export/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS']
            expose_headers: ['Content-Disposition', 'Content-Type']
            max_age: 3600    